# (PART\*) Introduction {-}

# Why a Hebrew Grammar course? {- #motivation}

If you are familiar with our ministry, you know our flagship course ***Hebrew Quest***, which introduces our students to the Jewishness of our Messiah and our Bible.

***Hebrew Quest*** was designed to get students into the Hebrew text as quickly as possible, with minimal focus on learning rules. For many of our students, this approach is quite successful; but, we also noticed other students began to drop off between lessons 12 and 16. These are the grammar lessons in between the Aleph-Bet (1-11) and the study passages (17-40). For some, these lessons were too much Hebrew grammar too fast, and for others it was not enough Hebrew grammar.

As we searched for a resource to recommend to these students, we noticed that they tended to fall into one of two camps:

1. <u>A workbook or a series of videos that are entirely self-paced/self-directed</u>. 
    * There may be some exercises, but generally tend to not be rigorous from an academic standpoint.
    * Additionally, with this format, there is no way for a student to get feedback on progress.
    
2. <u>Academic/Seminary level textbooks and courses</u>. 
    * These materials are __extremely__ rigorous with copious amounts of reading, rote memorization of paradigms, and in the case of courses, lectures and exams
    * The textbooks generally are much more detailed and advanced than most of our students need (or would enjoy). For example, there is usually an emphasis on Hebrew writing, such as learning how to convert a noun from singular to plural.
    * The pace of these courses is usually fast, and the stress level is high, focusing on due dates and grades.

Additionally, with either option, our students would incur additional fees to purchase these materials. This is something we wanted to avoid.

Although many of the resources we researched are top-notch, they were not quite what we were seeking for our students.

<div align="right">_(continued)_</div>

## Grammar course wishlist {- #our_course}

---

So what _were_ we seeking?

* In terms of content and rigor, the course would be academically challenging, but it would still be enjoyable with a low-stress level.
* The course would be self-paced for independent learning but provide feedback and encouragement.
* The course must align with our [Holy Language Learning Philosophy](https://holylanguage.com/learning-philosophy.php): emphasize active forms of learning over tons of reading and long lectures. It should seamlessly mesh with _Hebrew Quest_.
* From a technological standpoint, the course must be inexpensive and straightforward to deliver and maintain, while at the same time being high-quality and visually pleasant.
* The course should be easy to use (and if at all possible, free) for our students.
* Most importantly, the course must be Yeshua-centered that approaches learning Hebrew grammar as a spiritual as well as an academic endeavor (which is also a big part of our Learning Philosophy).

We couldn't find a course like this...so we BUILT it ourselves!

### Welcome to Hebrew GRAMMAR Quest - Experience Biblical Hebrew Grammar, the Holy Language Way! {-}

