# Quick Start Instructions {.unnumbered #get_started}

These instructions will get you up and running with the course.  We do encourage you to read the other introductory materials before you tackle Lesson 1.

> **Anki NOTE**: Eventually, you can do all work from a mobile device.  _For the initial Anki install, you do need to do these steps from a desktop or laptop_.  The Hebrew GRAMMAR Quest Anki deck can only be imported into the desktop Anki application. 


1. Download and install the [free Ezra SIL font](https://software.sil.org/downloads/r/ezra/EzraSIL-2.51.zip ){target="_blank"}.
1. INSTALL ANKI
    1. [Sign up for a free Ankiweb account here](https://ankiweb.net/account/register){target="_blank"}.
        * This allows you to synch your data from your desktop app to the cloud and to your phone or tablet
    1. [Download and Install the Anki Program (Mac/PC/Linux)](https://apps.ankiweb.net/){target="_blank"}.
    1. [Download the Hebrew GRAMMAR Quest (Preview Version) Anki Deck](./images/Hebrew Grammar Quest PREVIEW.apkg){target="_blank"}
    1. Change the Anki settings [as described here](#anki_settings).
    1. As desired, download the Anki app to your phone or tablet.  
        1. The [Android app](https://play.google.com/store/apps/details?id=com.ichi2.anki){target="_blank"} is free
        1. The [iOS app](https://itunes.apple.com/us/app/ankimobile-flashcards/id373493387?mt=8&ign-mpt=uo%3D4){target="_blank"} is $25 - see discussions in the Appendix for additional discussion as to whether the cost is "worth it"
        1. Synch
            1. In your desktop Anki app, click on synch (enter ankiweb credentials) - you probably want "upload to ankiweb" if asked.
            1. In your mobile app do the same, except here click "download from Ankiweb"
            1. Be sure to repeat the process if you go back and forth between mobile and desktop (be very careful when you select "upload to" or "download from" to make sure your information is flowing in the correct direction!)
1. Download the [course checklist](https://docs.google.com/spreadsheets/d/1t0C7JlygyUqgF_aQWbhq7h3s_VDn0VuvISJn5mp-LdE/edit?usp=sharing){target="_blank"} for you to keep track of your progress in this course.
    * Make a copy:
        * Click `File` then select `Make a copy` to save a copy to your personal Google Drive (recommended)
        * Click `File` then choose `Download` to save a copy to your local computer (you may lose the checkbox functionality when you do this)
        * (PLEASE <u>DO NOT</u> `Request Edit Access`)

    

> Let's get started!
