# (PART) Hebrew Nouns {-}

# END OF PREVIEW/DEMO COURSE {-}

Please [report errors, omissions, comments, or suggestions here](#report_issue)

The anticipated full course availability date is Q2 2021.

Sign up to receive ministry updates and other news at our [Holy Language Institute website](https://holylanguage.com).

Additional topics to be covered in the full ***Hebrew GRAMMAR Quest*** book/course:

4 Hebrew Nouns  
5 Definite Article and Conjunction Vav   
6 Hebrew Prepositions   
7 Hebrew Adjectives   
8 Hebrew Pronouns  
9 Hebrew Pronominal Suffixes   
10 Hebrew Construct Chain   
11 Numerals/counting  
12 Introduction to Hebrew Verbs   
13 Qal Perfect - Strong Verbs   
14 Qal Perfect - Weak Verbs  
15 Qal Imperfect - Strong Verbs  
16 Qal Imperfect Weak   
17 Vav Consecutive   
18 Qal Imperative   
19 Pronominal Suffixes on Verbs  
20 Qal Infinitive Construct    
21 Qal Infinitive Absolute   
22 Qal Participle   
23 Hebrew Syntax  
24 The Niphal Stem - Strong Verbs   
25 The Niphal Stem - Weak Verbs   
26 The Piel Stem - Strong Verbs   
27 The Piel Stem - Weak Verbs  
28 The Pual Stem - Strong Verbs   
29 The Pual Stem - Weak Verbs  
30 The Hiphil Stem - Strong Verbs   
31 The Hiphil Stem - Weak Verbs  
32 The Hophal Stem - Strong Verbs   
33 The Hophal Stem - Weak Verbs  
34 The Hithpael Stem - Strong Verbs   
35 The Hithpael Stem - Weak Verbs  

# Volunteers needed! {-}

If you like what you see, you can be a part of the next stages of the project - building out lessons 4-35!

Essentially, all of the "ACTIVities" need to designed.

<small>

| Section                                                             | Need                                                                                       | Estimated Time                                                      | Notes                                                                                                                                                                                                                                                                                                                                      |   |
|---------------------------------------------------------------------|--------------------------------------------------------------------------------------------|---------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|
| Lesson Prayer                                                       | Compose a prayer with relevant Bible verse                                                 | 15-30 minutes per Lesson                                            |                                                                                                                                                                                                                                                                                                                                            |   |
| Ruth Pursuit                                                        | Instructions to students and answer key                                                                   | 1 - 1.5 hours per lesson                                           | We have a few ideas drafted for each lesson, but these need   refining and validating to make sure the “object” of the scavenger hunt   actually can be found in Ruth 1-then highlight answers and create a PDF                                                                                                                                                                    |   |
| Capture Hebrew Text for Study Verses and Verse Warm-up activities | We have a list of Bible verses for which we need to load the   WLC text into a spreadsheet | 10-20 minutes per lesson (~13-17 verses per lesson)                 | The original materials we have for the Study Verses are   copyrighted by the publishers of Basics of Biblical Hebrew,   but https://tanach.us has a very generous reuse policy, so we’re   using their version of the WLC Hebrew Text, and then the NASB (also a   generous reuse policy) for English in our Anki Cards and warm-up videos |   |
| Anki Aerobics                                                       | QA testers  - identify   typos, opportunities to clarify questions and answers             | varies                                                              | If anyone happens to have experience editing Anki cards, we   have work!                                                                                                                                                                                                                                                                   |   |
| Worksheets                                                          | Evaluate whether a student could benefit from an additional   worksheet                    | Initial research: 5-10 minutes per lesson                           | There are a few free sites we check - depending on the   copyright, we can sometimes use that material directly                                                                                                                                                                                                                            |   |
| Worksheets                                                          | Design new worksheet                                                                       | Recreating a worksheet (if we need to): potentially 30-60   minutes | If we like someone else's worksheet but it's copyright, we can   take the germ of the concept and redesign it as our own product (giving   credit to the original creator, as needed)                                                                                                                                                      |   |
| Quest Quiz                                                          | Build Quizzes in Google Forms                                                              | 60 minutes per lesson                                               | We have most of the quiz questions in PDF format; it's just a   matter of retyping them in Google                                                                                                                                                                                                                                          |   |
| Word and Verse Warm-ups                                             | Create Powerpoint file with Hebrew/English/Izzy's audio - then   export as video           | 10-15 minutes per lesson for both videos                            | We have all of the materials - it's just a matter of inserting   each on a slide                                                                                                                                                                                                                                                           |   |
| General content                                                     | Proofreading, checking links, etc                                                          | 1-2 hours per lesson                                                |                                                                                                                                                                                                                                                                                                                                            |   |
| Twelve Tribes Badges                                                | Copy the Asher Google Form and reformat for the   remaining 11 tribes                      | 2-4 hours total for the   remaining tribes                          |                                                                                                                                                                                                                                                                                                                                            |   |

</small>

Email holylanguagecourses@gmail.com if you have an interest in getting involved with Hebrew GRAMMAR Quest!
    