# More Hebrew Quest and Hebrew GRAMMAR Quest FAQ{- #hq_hgq_faq}

* [What is the difference between Hebrew Quest and Hebrew GRAMMAR Quest?](#difference)
* [Do I need to complete Hebrew Quest before I start Hebrew GRAMMAR Quest?](#complete_hq_first)
* [When I complete this course, should I go back and finish Hebrew Quest?](#need_to_finish_hq)
*  [I haven't started either course.  Which should I do first?](#which_first)

<!-- Grammarly check: 10/24/2020 108 lines -->

## What is the difference between Hebrew Quest and Hebrew GRAMMAR Quest? {- #difference}

* Both courses are born of the same Holy Language Learning philosophy: the optimal method to interact with the Sacred Scriptures is by *doing*
* Hebrew Quest was intentionally designed to get students into Hebrew texts with as little "grammar" as possible
* Hebrew GRAMMAR Quest is designed to fill a gap for those students who want to know more about the inner workings of Hebrew but wish to do so in a fun, low-pressure format (as opposed to taking a formal Hebrew course or trying to read an academic-level textbook on their own)
* Also, we know that everyone learns a little differently
    * Many can view the 40 lessons of Hebrew Quest, and they "get it" concerning Hebrew
    * Others may have found themselves getting stuck on the "grammar" sections of Hebrew Quest and need some more in-depth grammar preparation before returning to the study passages
    * Still others made it through some or all of Hebrew Quest and have a desire to know more
* [As we said earlier](#hgq_and_hq), wherever you find yourself, if you are interested in digging deeper, you have come to the right place!

## Do I need to complete Hebrew Quest before I start Hebrew GRAMMAR Quest? {- #complete_hq_first}

* Emphatically - **No!** 
    * This grammar course starts from the beginning (with learning the Aleph-bet) and assumes no prior knowledge of Hebrew
* With that said, the more of Hebrew Quest you have completed, the more comfortable you may find it is to work through the grammar material
* If we were to categorize as "good," "better," "best" in terms of Hebrew Quest completion, here's what we would say:
    * **Good**: 
        * You have completed some or no Hebrew Quest lessons  
        * This means that the first three lessons of Hebrew GRAMMAR Quest might take you a little longer, but once you have that foundation, you'll be up to speed
    * **Better**: 
        * You have completed through Hebrew Quest Lesson 12 (the Aleph-bet and Vowels)  
        * This means the first three lessons will go a little more quickly for you
    * **Best**: 
        * You have completed through Lesson 15 (verbs) and beyond
        * This means that more of the concepts presented in Hebrew GRAMMAR Quest will tend to be things you have heard before versus brand new

## When I complete this course, should I go back and finish Hebrew Quest? {- #need_to_finish_hq}

> Hebrew GRAMMAR Quest is an extension of Hebrew Quest, not a substitute.

* So the answer to the question is, **ABSOLUTELY!**
* In fact, the most logical next step after completing a first-year Hebrew grammar course is to dig into the Scriptures and start reading.
* Hebrew Quest, starting with Lesson 16, is all about reading Hebrew<small>^[<small>Although, with your more in-depth knowledge, you may be able to go a little faster. If the Hebrew Quest videos are too slow for you, click the "Settings" gear icon in the bottom right corner of the video, click "Speed," and then select a faster speed.</small>]</small>.
* To say it differently, Hebrew Quest and Hebrew GRAMMAR Quest complement one another in a circular (and maybe slightly paradoxical!) form:
    * The more Hebrew Quest you have completed, the more you will get out of Hebrew GRAMMAR Quest, and
    * The more Hebrew GRAMMAR Quest you have completed, the more you will get out of Hebrew Quest
    * Either way, you can't go wrong!  The most important thing is to start.

## I haven't started either course.  Which should I do first? {- #which_first}

* If the word "grammar" makes your stomach churn, then start with (and stick with) **Hebrew Quest**!
* Otherwise, we can suggest doing the first 16 lessons of **Hebrew Quest** - this will take you in-depth through the Aleph-bet and give you an overview of Grammar and give you an introduction to reading Proverbs.
    * Also plan to do Hebrew Quest Memrise or Anki so you can pick up your first two Certificates as outlined [here](https://holylanguage.com/graduate.html)
* Then hop over to this course and get a firm foundation of Hebrew grammar
* Then go back to Hebrew Quest lesson 17 and the study passages will have extra life for you
* This will likely take you a long time to complete both<small>^[<small>It probably is not entirely unreasonable to be able to do two lessons per week, but be prepared to spend a LOT of time in Anki (or Memrise, for Hebrew Quest).  One lesson per week is probably a better pace.  In any case remember you get out of it what you put into it.  It's a marathon, not a sprint!</small>]</small>, but remember the proverb about the best time to plant a tree:  "The best time was 20 years ago.  The second-best time is today."
    
Whichever direction you take, we would encourage you to ultimately complete both **Hebrew Quest** and **Hebrew GRAMMAR Quest**.

