# Other FAQ {#other_faq}

* [There are many books out there to learn Hebrew.  What makes Hebrew GRAMMAR Quest different?](#hgq_difference)
* [What are the course Activities?](#activities_faq)
* [Will I be required to buy anything?](#buy_materials)
* [Who will (and who might not) benefit from Hebrew GRAMMAR Quest?](#who_benefits)
* [What if I am a Bible teacher? Should I take this course?](#bible_teacher)

## There are many books out there to learn Hebrew.  What makes Hebrew GRAMMAR Quest different? {- #hgq_difference}

* As we say above, we want students to learn by **doing**
    * While **Hebrew GRAMMAR Quest** will cover the same concepts as a typical first-year Hebrew textbook, the instructional design team at Holy Language Institute are big proponents of _active_ learning as opposed to passive learning
    * Reading a book is mostly a passive activity 
    * Therefore, our goal for this interactive, self-contained book is to provide a quick orientation to the concepts<small>^[<small>If you're looking for a stand-alone textbook, there is none better than <u>Basics of Biblical Hebrew</u>.</small>]</small>
* Textbooks have their place, but in our view, your "real" learning will take place when you complete the ACTIVities (see the root of the word "active" in there?)
    * This is the impetus behind the current "flipped classroom" philosophy in traditional education


## Will I be required to buy anything? {- #buy_materials} 

* **NO**.  Other than being a subscriber to Holy Language Institute, you will not need to purchase anything for this course (unless you want to)
* We would like to disclose that the iOS version of the Anki app requires a one-time purchase through the Apple store of $25
    * Note: Holy Language Institute has nothing to do with this policy and receives nothing should you decide to purchase the app
    * The developers of Anki provide every other platform for free and say they use the proceeds from the iOS app to fund these different platforms and program enhancements
    * While the price is steep for an app, most online reviews say the cost is justified (a few pennies a day over a year)
    * If you have an Apple device and do not wish to purchase the app, you may use a web-based version of mobile Anki at no charge (you won't be able to use it offline)

* There are lots of additional resources available that accompany Basics of Biblical Hebrew for free and to purchase - we will incorporate many of the free resources into this book package
* In other words, we have designed this book so that you should not need to purchase any additional learning materials
* With that said, if you wish to purchase _Basics of Biblical Hebrew_ or any of the accompanying resources for a more in-depth Grammar study, some options are below<small>^[<small>Before purchasing, we would like to make our students aware that the authors of these materials take an academic, as opposed to a reverential approach regarding God's Holy Name. You will see the transliteration of the Tetragrammaton printed on nearly every page.  While we believe this is unfortunate and unnecessary, Basics of Biblical Hebrew remains an excellent resource for an in-depth study of first-year Hebrew grammar.</small>]</small> 
    * [Basics of Biblical Hebrew Textbook](https://www.amazon.com/gp/product/031053349X/&tag=holylanginst-20)
    * [Basics of Biblical Hebrew Workbook](https://www.amazon.com/gp/product/0310533554/&tag=holylanginst-20)
    * [Basics of Biblical Hebrew Laminated Reference Card](https://www.amazon.com/gp/product/031026295X/&tag=holylanginst-20)
    * We would appreciate it if you would use one of the affiliate links, which allows Holy Language Institute to receive a small commission
    
## Who will (and who might not) benefit from Hebrew GRAMMAR Quest? {- #who_benefits}

* Hebrew GRAMMAR Quest is focused on reading and understanding Hebrew for the English speaker.
    * If you desire to read the Hebrew Scriptures in the original language and have a greater comprehension of what you read, this course is for you!
    * If one was looking to be a fluent writer or speaker<small>^[<small>There are speaking activities beginning with Lesson 3, but this is more to engage additional senses in the learning process and not to become a fluent reader.</small>]</small> of Hebrew, or teach Hebrew in a formal academic setting, this course probably would not fully meet that person's goals (although it would be a terrific first step).
* This course focuses on Biblical Hebrew, not Modern Hebrew.
    * If you are looking to translate "can you direct me to the railway station?", we apologize, but this course will not benefit you!
* Hebrew GRAMMAR Quest is designed to be self-directed and (mostly) stress-free.
    * By design, it does not have the accountability and rigor of a traditional academic program.
        * By saying it does not have "academic rigor," we are **NOT** saying this course will be __easy__.
        * You will likely spend _many_ hours on this course, mostly in Anki.
        * We believe it will be a tremendous investment you can make for the kingdom and the impact you can have on others.
        * When you start to see your knowledge building up in Anki, we believe you will find it rewarding and fun as well.
    * Those who are seeking more of an academic/seminary type of setting might fare better with a traditional, instructor-led, Hebrew course (but the more of THIS course you complete, the easier THAT course will be!).
    
## What if I am a Bible teacher? Should I take this course? {- #bible_teacher}

* We believe this course, in conjunction with **Hebrew Quest**, would prepare a pastor or teacher of a traditional Christian or Messianic congregation to have a basic understanding of the Hebrew text to be able to exegete and communicate beginning and intermediate level Hebrew/Hebraic concepts to a lay audience.
    * Additionally, for those who have had first-year Hebrew at seminary (perhaps many years ago) but have struggled to apply knowledge of the original language to their vocation, or for those pastors/teachers who may have never taken a grammar course in Hebrew, ***our prayer is that this course, along with Hebrew Quest, will give new life to Hebrew application in that person's teaching ministry***<small>^[<small>This book's compiler can testify to this!</small>]</small>.