# Appendix B: Questions and Answers about Hebrew GRAMMAR Quest {-}



## What is the difference between Hebrew Quest and Hebrew GRAMMAR Quest? {-}

* Both courses are born of the same Holy Language Learning philosophy: the optimal way to interact with the Sacred Scriptures is by *doing*

* Hebrew Quest was intentionally designed to get students into Hebrew texts with as little "grammar" as possible.

* Hebrew GRAMMAR Quest is designed to fill a gap for those students who want to know more about the inner workings of Hebrew, but wish to do so in a fun, low pressure format (as opposed to taking a formal Hebrew course or trying to read a textbook on their own).

* Also, we know that everyone learns a little differently
    * Many are able view the 40 lessons of Hebrew Quest, and they "get it" with respect to Hebrew
    * Others may have found themselves getting stuck on the "grammar" sections of Hebrew Quest and need some more in-depth grammar preparation before returning to the study passages
    * Still others made it through some or all of Hebrew Quest and just have a desire to know more

* Wherever you find yourself, if you have an interest in digging deeper, you have come to the right place!

## Do I need to have completed Hebrew Quest before I start Hebrew GRAMMAR Quest? {-}

* Emphatically - **No!** 
    * This grammar course starts from the beginning (with learning the Aleph-bet) and assumes no prior knowledge of Hebrew.
* With that said, the more of Hebrew Quest you have completed the easier you may find it is to work through the grammar material.

* If we were to categorize as "good", "better", "best" in terms of Hebrew Quest completion, here's what we would say:
    * **Good**: 
        * You have completed some or no Hebrew Quest lessons.  
        * This means that the first three lessons of Hebrew GRAMMAR Quest might take you a little longer, but, once you have that foundation, you'll be up to speed.
    * **Better**: 
        * You have completed through Hebrew Quest Lesson 12 (the Aleph-bet and Vowels).  
        * This means the first three lessons will go a little more quickly for you.
    * **Best**: 
        * You have completed through Lesson 15 (verbs) and beyond
        * This means that more of the concepts presented in Hebrew GRAMMAR Quest will tend be things you have heard before, versus brand new.

## When I complete this course, should I go back and finish Hebrew Quest? {-}

* **ABSOLUTELY!**
* In fact, the most logical next step after completing a first year Hebrew grammar course is to dig into the Scriptures and start reading.  
* Hebrew Quest, starting with Lesson 16 is all about reading Hebrew^[Although, with your deeper knowledge you may be able to go a little faster.If the Hebrew Quest videos are too slow for you, click the "Settings" gear icon in the bottom right corner of the video, then click "Speed", and then select a faster speed]
* In other words, Hebrew Quest and Hebrew GRAMMAR Quest compliment each other in a circular (and maybe slightly paradoxical) way:
    * The more Hebrew Quest you have completed, the more you will get out of Hebrew GRAMMAR Quest, and
    * The more Hebrew GRAMMAR Quest you have completed, the more you will get out of Hebrew Quest
    * Either way, you can't go wrong!

## There are many books out there to learn Hebrew.  What makes Hebrew GRAMMAR Quest different? {-}

* As we say above, we want students to learn by **doing**
    * While **Hebrew GRAMMAR Quest** will cover the same concepts as a typical first-year Hebrew textbook, the instructional design team at Holy Language Institute are huge proponents of _active_ learning as opposed to passive learning.
    * Reading a book is largely a passive activity. Therefore, our goal for this book and the accompanying lectures, is to simply provide a quick orientation to the concepts.^[In fact, if you're looking for a stand-alone textbook, there is none better than <u>Basics of Biblical Hebrew</u>.]

* Textbooks have their place, but in our view, your "real" learning will take place when you complete the ACTIVities (see root of the word "active" in there?).  This is the impetus behind the current "flipped classroom" philosophy in traditional education.

## What is a "flipped classroom"? {-}

* Hebrew GRAMMAR Quest applies concepts from what is called a "flipped classroom"
* In a traditional classroom, lecture and exams are the priority
    * What educators have started to notice was that these two aspects of teaching, though valuable for different reasons, are not when the student's primary learning occurs
* In a flipped classroom, the activities usually thought of as "homework" are the priority
    * Interactive reading (with note-taking and active-recall), worksheets, and discussion are much better vehicles for learning than a lecture
* Therefore in Hebrew GRAMMAR quest there is an intentional de-emphasis on lectures and exams and an intentional emphasis on activities


## What are the activities? {-}

* First and foremost, there is the Anki deck; and it's, well..., massive
    * See the appendix for a discussion on Anki if you are not familiar with it
* Anki is based on active recall and it has been described as one of the best ways to "upload information to your brain"
* Each lesson will also have a **Ruth Pursuit** 
    * You may remember in Hebrew Quest, when Izzy was teaching the aleph-bet, and part of your quest was to "bag" each letter by reading a passage of scripture
    * We are continuing that, with using Ruth chapter 1 as our anchor text.
* Certain lessons may also have other activities, such as worksheets for you to complete

## How do I access the Anki deck or online course? {-}

* The full program including the Anki package and access to the online course, are available to subscribers of Holy Language Institute 
* Login to [holylanguage.com](holylanguage.com)
* Click on the LEARN button then select "Hebrew GRAMMAR Quest" ***(pending development)***

## Will I need to buy anything? {-} 

* **NO**.  Other than being a subscriber to Holy Language Institute, you will not need to purchase anything for this course (unless you want to)
* We would like to disclose that the iOS version of the Anki app requires a one-time purchase through the Apple store of $25
    * Note: Holy Language Institute has nothing to do with this policy and receives nothing should you decide to purchase the app
    * The developers of Anki provide every other platform for free, and say they use the proceeds from the iOS app to fund these other platforms and program enhancements
    * While the price is steep for an app, most online reviews say the cost is justified (a few pennies a day over the course of a year)
    * If you have an Apple device and do not wish to purchase the app, you may use a web-based version of mobile Anki at no charge (you just can't use it offline)

* There are lots of additional resources available that accompany Basics of Biblical Hebrew for free and to purchase - we will incorporate many of the free resources into the online course
* In other words, we have designed this course so that you should not have a need to purchase anything additional by way of learning materials
* With that said, if you wish to purchase _Basics of Biblical Hebrew_ or any of the accompanying resources for deeper study, some options are below^[We would like to make our students aware that the authors of these materials take an academic, as opposed to a reverential approach regarding God's Holy Name and you will see the transliteration of the Tetragrammaton printed on yearly every page.  While we believe this is unfortunate and unnecessary, Basics of Biblical Hebrew remains an excellent resource for first-year Hebrew grammar] 
    * [Basics of Biblical Hebrew Textbook](https://www.amazon.com/gp/product/031053349X/&tag=holylanginst-20)
    * [Basics of Biblical Hebrew Workbook](https://www.amazon.com/gp/product/0310533554/&tag=holylanginst-20)
    * [Basics of Biblical Hebrew Laminated Reference Card](https://www.amazon.com/gp/product/031026295X/&tag=holylanginst-20)
    * We would appreciate it if you would use one of the affiliate links, which allows Holy Language Institute to receive a small commission
    
## Who will (and who might not) benefit from Hebrew GRAMMAR Quest? {-}

* Hebrew GRAMMAR Quest is focused on reading and understanding Hebrew for the English speaker
    * If you desire to read the Hebrew Scriptures in the original language and have a greater comprehension of what you read, this course is for you!
    * If one was looking to be a fluent writer or speaker of Hebrew, or teach Hebrew in an academic setting, this course probably would not fully meet that person's goals (although it would be a great first step)
    
* This course focuses on Biblical Hebrew, not Modern Hebrew
    * If you are looking to translate "can you direct me to the railway station?", we apologize, but this course will not benefit you!
    
* Hebrew GRAMMAR Quest is designed to be self-directed and (mostly) stress-free; by design, it will not have the accountability and rigor of a traditional academic program
    * You will spend many hours on this course - we believe it will be a tremendous investment you can make for the kingdom and the impact you can have on others; when you start to see your knowledge building up in Anki, we believe you will find it rewarding and perhaps even fun as well
    * Those who seeking more of an academic/seminary type of setting might fare better with a traditional, instructor-led, Hebrew course
    
### What if I am a Bible teacher? Should I take this course? {-}

* We believe this course, in conjunction with Hebrew Quest, would prepare a pastor or teacher of a traditional Christian congregation to have a basic understanding of the Hebrew text to be able to exegete and communicate higher-level Hebrew/Hebraic concepts to a lay audience
    * Additionally, for those who have had first-year Hebrew at seminary (perhaps many years ago) but found it meaningless to their vocation, or for those pastors/teachers who may have never taken a grammar course in Hebrew, our prayer is that this course will give new life to Hebrew application in that person's teaching ministry
    * Conversely, if you are leading a congregation sophisticated with Hebrew and will be frequently reading from Torah, such as at a synagogue, you may benefit from formal Hebrew training instead of, or in addition to Hebrew GRAMMAR Quest.